### ISSUE TITLE
Issue with AllAsync

### ISSUE THREAD

**Issue by kevinandrewsde** [zzzprojects/LINQ-Async#1]
AllAsync implementation always returns "True" when using an async Predicate:

```
        private static async Task MainAsync()
        {
            var array = new[] { 0, 1 };
            var res = await array.AllAsync(async x => await DoWork(x) == 0);
            Debug.WriteLine(res);
        }

        private static Task<int> DoWork(int x)
        {
            return Task.FromResult(x - 1);
        }
```

**Comment by JonathanMagnan** [comment]
Hello @ikaros88 ,

Are you sure this method is coming from our library? The code seems not compiling.

I do not remember supporting async predicate, but I may be wrong since I have not touched this library for a long time.

Best Regards,

Jonathan

**Comment by kevinandrewsde** [comment]
Hi Jonathan,

I am sure that the method is from your library, the implementation can be found here:
[AllAsync.cs](https://github.com/zzzprojects/LINQ-Async/blob/master/src/Z.Linq.Async/EnumerableAsync/PredicateAsync/Immediate_Enumerable_AsyncFunc/IEnumerable%60/AllAsync.cs)
I am currently using FirstOrDefaultAsync, AnyAsync, WhereAsync, SingleAsync from your library, they all work perfectly, both in a real world project and also in small test cases such as the one above. Only AllAsync is always true as soon as the predicate is a Task<bool>.

Greetings

**Comment by JonathanMagnan** [comment]
Hello @ikaros88 ,

You are right. I was probably still sleeping and opened a very old project.

We can successfully reproduce the issue. The problem happens because we treat the predicate in the All function like a filter. All result that returns false is filtered and skipped.

We will try to release a fix for Monday.

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @ikaros88 ,

The v1.0.1 has been released
https://www.nuget.org/packages/Z.Linq.Async/

Let me know if the AllAsync method is now working correctly.

Best Regards,

Jonathan

**Comment by kevinandrewsde** [comment]
Hi Jonathan,

everything works perfectly now, thanks a lot!

Greetings
