### ISSUE TITLE
Add package targeting .NET Standard

### ISSUE THREAD

**Issue by awesomeunleashed** [zzzprojects/LINQ-Async#2]
Portable class libraries are now Legacy because of the existence of .NET Standard. Currently a .NET Standard 2.0 class library project can reference the Z.Linq NuGet package, but not without warnings about the package using .NET Framework 4.6.1.

I'm pretty sure a .NET Standard version of this library would work fine (2.0 builds without changes, and 1.0 builds if you remove the System.Diagnostics.Contracts usage in OrderByCompletion.cs). If so, it would be nice if you could add a netstandard-targeting package to the NuGet feed.

**Comment by JonathanMagnan** [comment]
Hello @awesomeunleashed,

Thank you for your suggestion, we will look at this request.

Best Regards,

Jonathan

---

**Performance Libraries**
`context.BulkInsert(list, options => options.BatchSize = 1000);  `
[Entity Framework Extensions](http://entityframework-extensions.net/) • [Bulk Operations](http://bulk-operations.net/) •  [Dapper Plus](http://dapper-plus.net/) •  [LinqToSql Plus](http://linqtosql-plus.net/)

**Runtime Evaluation**
`Eval.Execute("x + y", new {x = 1, y = 2}); // return 3`
[C# Eval Function](http://eval-expression.net/) • [SQL Eval Function](http://eval-sql.net/)

**Comment by paaltuv** [comment]
Second this request. Would be great.

**Comment by JonathanMagnan** [comment]
Hello @paaltuv , thank you for the reminder and sorry @awesomeunleashed  for forgetting about this request.

The v1.0.3 has been released.

The package should now be compatible with .NET Standard 2.0

Best Regards,

Jonathan

**Comment by JonathanMagnan** [comment]
Hello @paaltuv , @awesomeunleashed ,

This issue will be closed since it has been resolved.

Feel free to reopen it if you feel otherwise.

Best Regards,

Jonathan
